export { HeroSection } from "./HeroSection";
export { DegreeSection } from "./DegreeSection";
export { MemoriesSection } from "./MemoriesSection";
export { ClubsSection } from "./ClubsSection";
export { ClosingSection } from "./ClosingSection";
export { C, StoryPageStyles, StoryWave } from "./shared";
export type { HeroAction, HeroSectionProps, HeroStat } from "./HeroSection";
export type { ClubItem, ClubsSectionProps } from "./ClubsSection";
export type { ClosingAction, ClosingSectionProps } from "./ClosingSection";
export type { DegreeCallout, DegreeHighlightCard, DegreeSectionProps } from "./DegreeSection";
export type { MemoriesSectionProps, MemoriesSupportCard } from "./MemoriesSection";
export type { MemoriesSlide, MemoriesSlideshowProps } from "./MemoriesSlideshow";
